apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: r-devops-magistracy-project-2sem-272184471
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
        location /api/ {
            proxy_pass http://sausage-backend:8080/api/;
            proxy_set_header Host $host;
        }
        location /cart {
            proxy_pass http://sausage-backend:8080/api/cart;
            proxy_set_header Host $host;
        }
        location /report/ {
            proxy_pass http://sausage-backend-report:8081/;
            proxy_set_header Host $host;
        }
    }
