FROM maven:3.8.4-openjdk-17-slim AS builder

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

# Используем sh вместо bash (alpine)
COPY --from=builder /usr/bin/env /usr/bin/env

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
