apiVersion: v2
name: sausage-store
description: Sausage Store Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: backend
    version: 0.1.0
  - name: backend-report
    version: 0.1.0
  - name: frontend
    version: 0.1.0
  - name: infra
    version: 0.1.0
