apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: {{ .Values.mongodb.port }}
        env:
        - name: MONGO_INITDB_DATABASE
          value: {{ .Values.mongodb.database }}
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongodb.username }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongodb.password }}
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mongodb.port }}
    targetPort: {{ .Values.mongodb.port }}
  selector:
    app: mongodb
