apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: sausage-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storage.size }}
  {{- if .Values.mongodb.storage.storageClass }}
  storageClassName: {{ .Values.mongodb.storage.storageClass }}
  {{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: sausage-store
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: {{ .Values.mongodb.port }}
          name: mongodb
        env:
        - name: MONGO_INITDB_DATABASE
          value: {{ .Values.mongodb.database }}
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongodb.username }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongodb.password }}
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        resources:
          {{- toYaml .Values.mongodb.resources | nindent 10 }}
  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.mongodb.storage.storageClass }}
      storageClassName: {{ .Values.mongodb.storage.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.mongodb.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mongodb.port }}
    targetPort: {{ .Values.mongodb.port }}
    name: mongodb
  selector:
    app: mongodb
