{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sausage-frontend-ingress-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sausage-frontend
            port:
              number: {{ .Values.service.port }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: sausage-backend
            port:
              number: 8080
      - path: /report
        pathType: Prefix
        backend:
          service:
            name: sausage-backend-report
            port:
              number: 8081
{{- end }}
