apiVersion: v1
kind: Service
metadata:
  name: sausage-backend-report
  namespace: {{ .Release.Namespace }}
  labels:
    app: sausage-backend-report
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
    name: http
  selector:
    app: sausage-backend-report
